version: '3.3'
services:
  app:
    image: gbbg123/actionboxd-node
    build: .
    ports: 
      - 80:3000
    environment:
      - MONGO_URI=mongodb://mongo_db/gbbg123/actionboxd-node
    networks: 
      - mernnodeapp
  db:
    image: mongo:4.2.1
    volumes:
      - mongo-db:/data/db
    networks:
      mernnodeapp:
        aliases:
          - "mongo_db"
networks:
  mernnodeapp:
    driver: bridge
volumes:
  mongo-db: